import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@ariadocs/react/styles/github.css"; // rehypePrism should be there in plugin for syntax highlight
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased max-w-3xl mx-auto py-8`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
