import { Navbar } from "@/components/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${inter.className} dark:text-neutral-200 dark:bg-zinc-950`}
      >
        <Navbar />
        <main className="w-[60%] mx-auto py-8 max-[1200px]:w-[90%] max-[800px]:w-[92%]">
          {children}
        </main>
      </body>
    </html>
  );
}
