import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@ariadocs/react/styles/github.css"; // rehypePrism should be there in plugin for syntax highlight
import { PropsWithChildren } from "react";
import { getDictionary, LangProps, locales } from "@/lib/i18n";
import { ClientDictionaryProvider } from "@/components/dict-provider";
import Navbar from "@/components/navbar";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: PropsWithChildren<LangProps>) {
  const { locale } = await params;
  const dict = await getDictionary(locale);
  return (
    <html
      lang={locale}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ClientDictionaryProvider dict={dict}>
          <Navbar />
          <section className="px-4">{children}</section>
        </ClientDictionaryProvider>
      </body>
    </html>
  );
}

export async function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}
